[package]
name = "ec2-reporter-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
futures = "0.3"
rusoto_core = "0.47.0"
rusoto_ec2 = "0.47.0"